<?php

namespace backend\models;

use Yii;
use yii\behaviors\SluggableBehavior;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "news".
 *
 * @property int $id
 * @property int|null $category_id
 * @property string $slug
 * @property string $title
 * @property string $description
 * @property int $enabled
 *
 * @property Category $category
 * @property TagToNews[] $tagToNews
 * @property Tag[] $tags
 */
class News extends \yii\db\ActiveRecord
{
    public $formTags;

    public static function tableName()
    {
        return 'news';
    }

    public function behaviors()
    {
        return [
            [
                'class' => SluggableBehavior::class,
                'attribute' => 'title',
                // 'slugAttribute' => 'slug',
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['category_id', 'enabled'], 'integer'],
            [['title', 'description'], 'required'],
            [['description'], 'string'],
            [['slug', 'title'], 'string', 'max' => 256],
            [['slug'], 'unique'],
            [['category_id'], 'exist', 'skipOnError' => true, 'targetClass' => Category::class, 'targetAttribute' => ['category_id' => 'id']],
            [['formTags'], 'filter', 'filter' => function ($value) { //Todo валидация массива
                return !(empty($value)) ? ArrayHelper::toArray($value) : [];
            }]
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'category_id' => 'Category ID',
            'slug' => 'Slug',
            'title' => 'Title',
            'description' => 'Description',
            'enabled' => 'Enabled',
        ];
    }

    /**
     * Gets query for [[Category]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getCategory()
    {
        return $this->hasOne(Category::class, ['id' => 'category_id']);
    }

    /**
     * Gets query for [[TagToNews]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getTagToNews()
    {
        return $this->hasMany(TagToNews::class, ['news_id' => 'id']);
    }

    /**
     * Gets query for [[Tags]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getTags()
    {
        return $this->hasMany(Tag::class, ['id' => 'tag_id'])->viaTable('tag_to_news', ['news_id' => 'id']);
    }

    public function afterFind()
    {
        parent::afterFind(); // TODO: Change the autogenerated stub
        $this->formTags = ArrayHelper::getColumn($this->tags, 'title');
    }

    public function afterSave($insert, $changedAttributes)
    {

        $transaction = Yii::$app->db->beginTransaction();

        parent::afterSave($insert, $changedAttributes);

        try {

            $this->unlinkAll('tagToNews', true);//то же самое TagToNews::deleteAll(['news_id' => $this->id]);

            foreach ($this->formTags as $tagTitle) { //Todo Берем все наши теги, проверяем нет тега в нашей таблице. Если нет то записываем его и сохраняем
                $tag = Tag::findOne(['title' => $tagTitle]);

                if (!$tag) {//если тега нет в таблице, то добавляем его
                    $tag = new Tag();
                    $tag->title = $tagTitle;

                    if (!$tag->save()) {
                        return false;
                    }
                }

                $this->link('tags', $tag);
            }
            $transaction->commit();

        } catch (\Exception $e) {
            $transaction->rollBack();
            throw $e;
        }

        return true;

    }
}
