<?php

namespace frontend\models;

use common\models\User;
use yii\behaviors\SluggableBehavior;
use yii\db\ActiveRecord;

class Comment extends ActiveRecord
{
    public static function tableName()
    {
        return '{{%comment}}';
    }
    public function beforeSave($insert)
    {
        $this->created_at = date('Y-m-d H:i:s');

        $this->user_id = \Yii::$app->user->identity->id;

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function rules()
    {
        return [
            [['description'], 'string', 'min' => 2, 'max' => 256],
            [['news_id'], 'integer'],
            [['user_id'], 'integer'],
        ];
    }

    public function getNews(){
        return $this->hasOne(News::class, ['id' => 'news_id']);
    }

    public function getUser(){
        return $this->hasOne(User::class, ['id' => 'user_id']);
    }
}